---
title: "My Webpage"
author: "Eugenie Euskirchen"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(leaflet)
```


#Read in salmon count file

```{r}
esc <-  read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", 
                 method = "libcurl"),
                 stringsAsFactors = FALSE)
```

#Calculate annual escapment for salmon species

```{r, results ='hide'}
species_list <- c("Chinook", "Sockeye","Chum", "Pink", "Coho")
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = F) %>% 
 mutate(Year = as.numeric(Year)) %>% 
 group_by(Year, SASAP.Region, Species) %>% 
 summarise(total_escapment = sum(DailyCount)) %>% 
 filter(Species %in% c("Chinook", "Sockeye", "Chum", "Pink", "Coho")) 
#the line of code above is the same as this line below:
#filter(Species == "Chinook" | Species == "Sockeye" | Species == "Chum" etc.)
head(annual_esc)
```

#Visualize Escapment
```{r, echo = FALSE}
ggplot(data = annual_esc, mapping = aes(x= Species, y = total_escapment,))+ geom_col( fill = "blue")
```

```{r}
ggplot(data = annual_esc, mapping = aes(x= Species, y = total_escapment, fill = SASAP.Region))+ geom_col()
```
```{r}
my_theme <- theme_void()+
  theme(legend.position = "bottom")
#ggplot(data = annual_esc %>% filter())
ggplot (data = filter(annual_esc, SASAP.Region == "Kodiak"),
  mapping = aes(x = Year, y = total_escapment, color = Species))+
  geom_point()+
  geom_line()+
  scale_color_brewer(palette = "Dark2")+
  ylab("Escapement (no. fish per year)")+
  ggtitle("Kodiak Salmon Escapment")
  #theme_bw()
  my_theme
```
Escapment over time: all regions
```{r, fig.width = 7, fig.height = 12, echo = FALSE}
fig1 <- ggplot(annual_esc, aes(x = Year, y = total_escapment, color = Species))+
  geom_point()+
  geom_line()+
  facet_wrap(~SASAP.Region, scales = "free_y", ncol = 1)
#free_y above frees the y-scale for uneven data
#Below: more than one column of data
#facet_wrap(~SASAP.Region, scales = "free_y")
my_theme

fig1
ggsave("figures/escapment.png", fig1, width = 12, height = 7, units ="in")

```

#Map sampling locations
Create a table with unique sampling locations, latitudes, and longitudes
```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()

head(locations)
```
```{r}
datatable(locations)
```
```{r, echo=FALSE}
datatable(locations)
```
```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(~Longitude,  ~Latitude, popup = ~Location)
```


```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)

```








